### ISSUE TITLE
Külön repó a scrapereknek

### ISSUE THREAD

**Issue by vlacko0930** [szentjozsefhackathon/katolikus-nepszamlalas#25]
Lehet célszerű lenne külön repót csinálni a scrapereknek, mert más célra is használhatóak. Subrepónak be lehet tenni mindenhova, ahol használhatóak.

Mi a legnagyobb előny? Ha frissül 1 honlapstruktúra, akkor minden könnyebben átveszi, elég 1 helyen szerkeszteni.

**Comment by borazslo** [comment]
Így így!

https://github.com/szentjozsefhackathon/sematizmus
